packages:
  attrs: sudo pip3 install attrs (19.3.0)
  capsul: sudo pip3 install capsul (2.2.1)
  cython: sudo pip3 install Cython (0.29.20)
  list_imports: sudo pip3 install list-imports (2019.6.12)
  lmfit: sudo pip3 install lmfit (1.0.1)
  matplotlib: sudo pip3 install matplotlib (3.2.2)
  nibabel: sudo pip3 install nibabel (2.5.2)
  nilearn: sudo pip3 install nilearn (0.5.2)
  nipype: sudo pip3 install nipype (1.5.0)
  niwidgets: sudo pip3 install niwidgets (0.2.2)
  nose: sudo pip3 install nose (1.3.7)
  numpy: sudo pip3 install numpy (1.19.0)
  pandas: sudo pip3 install pandas (1.0.5)
  pyqt5: sudo pip3 install pyqt5 (5.14.2)
  scikit-image: sudo pip3 install scikit-image (0.17.2)
  scikit-learn: sudo pip3 install -U scikit-learn (0.20.4)
  scipy: sudo pip3 install scipy (1.5.1)
  sip: sudo pip3 install sip (5.3.0)
  sympy: sudo pip3 install sympy (1.6.1)
  traits: sudo pip3 install traits (5.2.0)
paths:
  data: /tmp/
  histories: []
  modules: modules
  projects: ../data
version: 20.07.07a
