packages:
  capsul: sudo pip3 install capsul ()
  cython: sudo pip3 install Cython (0.29.14)
  list_imports: sudo pip3 install list-imports (2019.6.12)
  matplotlib: sudo pip3 install matplotlib (3.1.3)
  nibabel: sudo pip3 install nibabel (2.4.1)
  nilearn: sudo pip3 install nilearn (0.5.2)
  nipype: sudo pip3 install nipype (1.4.1)
  niwidgets: sudo pip3 install niwidgets (0.2.2)
  nose: sudo pip3 install nose ()
  numpy: sudo pip3 install numpy (1.18.1)
  pandas: sudo pip3 install pandas ()
  pyqt5: sudo pip3 install pyqt5 (5.14.1)
  scikit-image: sudo pip3 install scikit-image (0.16.2)
  scikit-learn: sudo pip3 install -U scikit-learn ()
  scipy: sudo pip3 install scipy ()
  sympy: sudo pip3 install sympy (1.1.1)
  traits: sudo pip3 install traits (5.2.0)
paths:
  data: /tmp/
  histories:
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/loopFor_recursif.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/If_structure.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/script_submod.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/script_submod_if.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/test_T2map.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/test_T1map.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/test_TImap.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/script_filtering_files.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/test_script_2.dgr
  - /home/domicile-xubuntu/Bureau/Projets_mri_works/script_polynome_2nd.dgr
  modules: modules
  projects: ../data
version: 20.04.24a
