packages:
  attrs: pip3 install attrs (19.3.0)
  capsul: pip3 install capsul (2.2.1)
  cython: pip3 install Cython (0.29.20)
  list_imports: pip3 install list-imports (2019.6.12)
  lmfit: pip3 install lmfit (1.0.1)
  matplotlib: pip3 install matplotlib (3.2.2)
  nibabel: pip3 install nibabel (2.5.2)
  nilearn: pip3 install nilearn (0.5.2)
  nipype: pip3 install nipype (1.5.0)
  niwidgets: pip3 install niwidgets (0.2.2)
  nose: pip3 install nose (1.3.7)
  numpy: pip3 install numpy (1.19.0)
  pandas: pip3 install pandas (1.0.5)
  pyqt5: pip3 install pyqt5 (5.14.2)
  pytest: pip3 install -U pytest (6.0.1)
  scikit-image: pip3 install scikit-image (0.17.2)
  scikit-learn: pip3 install -U scikit-learn (0.20.4)
  scipy: pip3 install scipy (1.5.1)
  sip: pip3 install sip (5.3.0)
  sympy: pip3 install sympy (1.6.1)
  traits: pip3 install traits==5.2.0 (5.2.0)
paths:
  data: /tmp/
  histories:
  - /home/omontigon/Documents/mri_works_projects/N4_Bias.dgr
  - /home/omontigon/Documents/mri_works_projects/N4_Bias_subMod.dgr
  - /home/omontigon/Documents/mri_works_projects/Matlab_engine.dgr
  modules: modules
  projects: ../data
version: 20.08.13a
